### ISSUE TITLE
Format exported data

### ISSUE THREAD

**Issue by adriantunez** [masweetman/export_docx#7]
Hi,

Currently the exported data is not formatted in Word (like tables, pre's, bold, italic, etc). Maybe it could be easily done using a  [ruby library/gem example](https://github.com/chrahunt/docx). 

Do you plan to add that feature in a near future?

**Comment by masweetman** [comment]
It can't be easily done with that gem. That gem can only deal with plain text. You'd need to convert the HTML to Word-formatted XML and insert it manually. I don't use markdown or textile in my issue descriptions so I don't have any motivation to do it.

**Comment by masweetman** [comment]
I suppose the only easy way would be to build an HTML file for the whole issue and export that as a doc. But you wouldn't be able to have customizable templates for that.
