### ISSUE TITLE
Undefined method 'lines' for nil

### ISSUE THREAD

**Issue by md1023** [masweetman/export_docx#8]
Trying to export page with cyrillic text, linked issues, commits and multiple notes with markdown text. I get 500 error, log says:
```
Started GET "/issues/2859/export_docx" for 192.168.200.106 at 2017-01-16 13:44:52 +0300
Processing by DocxController#issue_export_docx as HTML
  Parameters: {"id"=>"2859"}
  Current user: Zzz (id=11)
Completed 500 Internal Server Error in 105ms (ActiveRecord: 22.8ms)

NoMethodError (undefined method `lines' for nil:NilClass):
  plugins/export_docx/app/helpers/docx_helper.rb:87:in `block (2 levels) in issue_to_docx'
  plugins/export_docx/app/helpers/docx_helper.rb:82:in `each'
  plugins/export_docx/app/helpers/docx_helper.rb:82:in `with_index'
  plugins/export_docx/app/helpers/docx_helper.rb:82:in `block in issue_to_docx'
  plugins/export_docx/app/helpers/docx_helper.rb:66:in `each'
  plugins/export_docx/app/helpers/docx_helper.rb:66:in `issue_to_docx'
  plugins/export_docx/app/controllers/docx_controller.rb:56:in `issue_export_docx'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

```
  Redmine version                3.3.0.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.6
```
Using unmodified `template_example.docx` file.

**Comment by adrianobr** [comment]
use redmine:passenger

**Comment by md1023** [comment]
Hi, where to set those login and password? I use Fedora, I've set
virtualhost parameter PassengerDefaultUser to apache - didn't help. It
isn't PostgreSQL configuration is it?

2017-01-16 20:48 GMT+03:00 Adriano Baptistella <notifications@github.com>:

**Comment by masweetman** [comment]
I fixed the undefined method issue in the last commit. Let me know if you have any more issues with export (besides handling markdown text--this plugin can't do that. It will export as plain text). Sorry I can't help you with your Passenger question; looks like you might have posted that here mistakenly. -Mike
