### ISSUE TITLE
Error when i want to configure the plugin

### ISSUE THREAD

**Issue by aganthie** [masweetman/export_docx#9]
Hi, I have installed your plugin for redmine but when I want to configure it, I have an iternal error.
I have searched what produce this error. 
It's in the file located at app/views/settings/_export_docx_settings.html.erb, replace <% @trackers = Tracker.all.order(:name) %> by <% @trackers = Tracker.order(:name).all %>.

**Comment by masweetman** [comment]
That should not be a problem. What is there error you were getting?

**Comment by aganthie** [comment]
This is the error : 
![image](https://cloud.githubusercontent.com/assets/23482935/23171148/fba6f4b8-f851-11e6-869f-44390e979936.png)

**Comment by masweetman** [comment]
What versions of Ruby/Rails are you using?

**Comment by aganthie** [comment]
Versions are :
 -Ruby 1.9.3-p551
 -Rails 3.2.19
 -Redmine 2.5.2

**Comment by masweetman** [comment]
Ah, that's why. You're using Rails 3. "all" returns something different in Rails 3 vs Rails 4 and I wrote my plugin for Rails 4.

**Comment by aganthie** [comment]
Ok thanks for your answer.
Maybe it could be a good idea to say that this plugin is made for Rails 4 in the documentation.

**Comment by masweetman** [comment]
You may want to upgrade. Redmine 2.x with Rails 3 is old, and ruby 1.9.3 isn't supported anymore by the ruby community
